/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1;

import com.mycompany.mavenproject1.model.MPTableModel;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class Panel3 extends javax.swing.JPanel {

    /**
     * Creates new form Panel3
     */
    public Panel3() {
        initComponents();
        
        this.setBounds(0, 0, 800, 600);
        this.setBackground(Color.LIGHT_GRAY);
        Object[][] datos = {
                {1, "A123", "B456", "C789", "12345", 1, "XYZ", "A123", "B456", "C789", "Descripción de Producto", "Unidad", 10, 1, 0.5},

            // Aquí colocarías tus datos
        };

        String[] columnas = {
            "No. Factura asociada",
            "Subpartida",
            "Complementario",
            "Suplementario",
            "Número de serie",
            "Número de ítem",
            "Código",
            "Subpartida",
            "Complementario",
            "Suplementario",
            "Descripción",
            "Tipo Unidad",
            "Cantidad Transformado",
            "Cantidad de Desperdicio",
            "Cantidad de Merma"
        };

        MPTableModel modelo = new MPTableModel(datos, columnas);

        this.jTable1.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
