/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.ui;

import com.mycompany.mavenproject1.database.model.Cliente;
import com.mycompany.mavenproject1.database.model.Material;
import com.mycompany.mavenproject1.database.model.MaterialReporte;
import com.mycompany.mavenproject1.database.repository.ClienteDAO;
import com.mycompany.mavenproject1.database.repository.MaterialDAO;
import com.mycompany.mavenproject1.database.repository.MaterialReporteDAO;
import java.util.List;

/**
 *
 * @author Sebas
 */
public class FormMaterialReporte extends javax.swing.JPanel {

    List<Material> insumos;
    MaterialReporteDAO mr = new MaterialReporteDAO();
    MaterialDAO md=new MaterialDAO();
    /**
     * Creates new form FormMaterialReporte
     */
    public FormMaterialReporte() {

        initComponents();
        cargarDatos();
    }

    public FormMaterialReporte(String codigo) {
        initComponents();
        cargarDatos();
        MaterialReporte materialReporte = mr.readByCodigo(codigo);
        System.out.println(materialReporte);
        this.txtMaterial.setText(materialReporte.getCodigo());
        var itemSelected=this.insumos.stream().filter(x->x.getDescripcion().equals(materialReporte.getDescripcion()));
                        //System.out.println(itemSelected.findAny().get().getDescripcion());

        this.comboInsumos.setSelectedItem(itemSelected.findAny().get());
       // this.comboInsumos.setSelectedIndex(materialReporte.getId());
    }

    public void cargarDatos() {
        MaterialDAO md = new MaterialDAO();

        insumos = md.readAll();
        insumos.stream().forEach(x -> this.comboInsumos.addItem(x));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboInsumos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaterial = new javax.swing.JTextField();

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jLabel1.setText("Insumo");

        jLabel2.setText("Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnGuardar)
                .addGap(32, 32, 32)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboInsumos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        MaterialReporteDAO mr = new MaterialReporteDAO();
        MaterialReporte material = new MaterialReporte();

        ClienteDAO cd = new ClienteDAO();
        Cliente client = cd.readByRuc(insumos.get(this.comboInsumos.getSelectedIndex()).getCliente().getRuc());
        material.setCliente(client);
        material.setCodigo(this.txtMaterial.getText());
        material.setCodigoInsumo(insumos.get(this.comboInsumos.getSelectedIndex()).getCodigo());
        material.setDescripcion(insumos.get(this.comboInsumos.getSelectedIndex()).getDescripcion());
        mr.create(material);
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Material> comboInsumos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMaterial;
    // End of variables declaration//GEN-END:variables
}
