/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.tablas;

import com.mycompany.mavenproject1.database.model.Material;
import com.mycompany.mavenproject1.database.model.MaterialReporte;
import com.mycompany.mavenproject1.database.repository.MaterialReporteDAO;
import com.mycompany.mavenproject1.tablas.model.MPReporteTableModel;
import com.mycompany.mavenproject1.tablas.model.MPTableModel;
import com.mycompany.mavenproject1.tablas.model.RenderTable;
import com.mycompany.mavenproject1.ui.FormMaterialReporte;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class TodosMaterialReporte extends javax.swing.JPanel {

    /**
     * Creates new form TodosMaterialReporte
     */
    public TodosMaterialReporte() {
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnNuevo = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        FormMaterialReporte fr = new FormMaterialReporte();
        JDialog dialog = new JDialog();
        dialog.setTitle("Insertar");

        dialog.getContentPane().add(fr);
        dialog.setSize(500, 400);
        dialog.setVisible(true);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                cargarDatos();
            }

        });


    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        var col = this.jTable1.getSelectedColumn();
        var row = this.jTable1.getSelectedRow();
        MaterialReporteDAO mr = new MaterialReporteDAO();
        if (col == 5) {

            var option = JOptionPane.showConfirmDialog(null, "Se va a eliminar el material");
            if (option == JOptionPane.YES_OPTION) {

                String codigo = this.jTable1.getModel().getValueAt(row, 0).toString();
                System.out.println(mr.delete(codigo));
                cargarDatos();
            }
            //System.out.println(this.jTable1.getModel().getValueAt(row, 0));
            //mr.delete();
        } else if (col == 4) {
            FormMaterialReporte fr = new FormMaterialReporte(this.jTable1.getModel().getValueAt(row, 0).toString());
            JDialog dialog = new JDialog();
            dialog.setTitle("Actualizar");

            dialog.getContentPane().add(fr);
            dialog.setSize(500, 400);
            dialog.setVisible(true);
            dialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    cargarDatos();
                }

            });

        }

    }//GEN-LAST:event_jTable1MouseClicked

    public void cargarDatos() {
        MaterialReporteDAO mr = new MaterialReporteDAO();

        JButton mod = new JButton();
        mod.setText("Modificar");
        mod.addActionListener((ActionEvent e) -> {
            System.out.println("Modificar");
        });
        JButton delete = new JButton();
        delete.setText("Eliminar");
        var materiales = mr.readAll();

        Object[][] datos = new Object[materiales.size()][WIDTH];
        for (int i = 0; i < materiales.size(); i++) {
            MaterialReporte materiaPrima = materiales.get(i);
            datos[i] = new Object[]{
                materiaPrima.getCodigo(),
                materiaPrima.getCodigoInsumo(),
                materiaPrima.getDescripcion(),
                materiaPrima.getCliente(),
                mod,
                delete
            };
        }
        //  mr.create(material);
        MPReporteTableModel modelo = new MPReporteTableModel(datos);
        //mr.readAll().stream().forEach(x -> this.jTable3.addr);
        this.jTable1.setModel(modelo);

        //this.jTable3.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(new JTextField()));
        // this.jTable1.setRowHeight(30);
        this.jTable1.setDefaultRenderer(Object.class, new RenderTable());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
