/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.tablas;

import com.mycompany.mavenproject1.database.model.Material;
import com.mycompany.mavenproject1.database.repository.MaterialDAO;
import com.mycompany.mavenproject1.database.repository.MaterialReporteDAO;
import com.mycompany.mavenproject1.tablas.model.MPTableModel;
import com.mycompany.mavenproject1.tablas.model.RenderTable;
import com.mycompany.mavenproject1.ui.FormMaterial;
import com.mycompany.mavenproject1.ui.FormMaterialReporte;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sebas
 */
public class TodosMaterial extends javax.swing.JPanel {

    /**
     * Creates new form TodosMaterial
     */
    public TodosMaterial() {
        initComponents();
        this.cargarDatos();
        this.jTable3.getTableHeader().setPreferredSize(new Dimension(10, 30));

        //List<List<Object>> datos2=List.of(List.of( "Algo","Algo","Algo","Algo","Algo","Algo","Algo","Algo","Algo", "SApo", "Perro", mod, delete));
        //this.jTable3.(columnClass, renderer);
    }

    private void cargarDatos() {

        JButton mod = new JButton();
        mod.setText("Modificar");
        mod.addActionListener((ActionEvent e) -> {
            System.out.println("Modificar");
        });
        JButton delete = new JButton();
        delete.setText("Eliminar");
        MaterialDAO mr = new MaterialDAO();
        var materiales = mr.readAll();
        Object[][] datos = new Object[materiales.size()][WIDTH];
        for (int i = 0; i < materiales.size(); i++) {
            Material materiaPrima = materiales.get(i);
            System.out.println(materiaPrima.getCoeficienteConsumo());
            datos[i] = new Object[]{
                materiaPrima.getCliente(),
                materiaPrima.getCodigo(),
                materiaPrima.getSubpartida(),
                materiaPrima.getDescripcion(),
                materiaPrima.getTipoUnidad(),
                materiaPrima.getSaldoInsumo(),
                materiaPrima.getPorcentajeDesperdicio(),
                materiaPrima.getPorcentajeMerma(),
                (materiaPrima.getCoeficienteConsumo() == null) ? "" : materiaPrima.getCoeficienteConsumo().doubleValue(),
                materiaPrima.getCalculaDesperdicio(),
                materiaPrima.getAplicaFormula(),
                mod,
                delete
            };
        }

        //  mr.create(material);
        MPTableModel modelo = new MPTableModel(datos);
        //mr.readAll().stream().forEach(x -> this.jTable3.addr);
        this.jTable3.setModel(modelo);

        //this.jTable3.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(new JTextField()));
        this.jTable3.setRowHeight(30);
        this.jTable3.setDefaultRenderer(Object.class, new RenderTable());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setLayout(new java.awt.BorderLayout());

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        this.cargarDatos();
    }//GEN-LAST:event_jPanel1FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormMaterial fr = new FormMaterial();
        JDialog dialog = new JDialog();
        dialog.setTitle("Insertar");

        dialog.getContentPane().add(fr);
        dialog.setSize(500, 400);
        dialog.setVisible(true);
        dialog.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                cargarDatos();
            }

        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        var col = this.jTable3.getSelectedColumn();
        var row = this.jTable3.getSelectedRow();
        MaterialDAO mr = new MaterialDAO();
        System.out.println(col);
                System.out.println(row);

        if (col == 12) {

            var option = JOptionPane.showConfirmDialog(null, "Se va a eliminar el material");
            if (option == JOptionPane.YES_OPTION) {

                String codigo = this.jTable3.getModel().getValueAt(row, 1).toString();
                mr.delete(codigo);
                cargarDatos();
            }
            //System.out.println(this.jTable1.getModel().getValueAt(row, 0));
            //mr.delete();
        } else if (col == 11) {
            FormMaterial fr = new FormMaterial();
            JDialog dialog = new JDialog();
            dialog.setTitle("Actualizar");

            dialog.getContentPane().add(fr);
            dialog.setSize(500, 400);
            dialog.setVisible(true);
            dialog.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    cargarDatos();
                }

            });

        }
    }//GEN-LAST:event_jTable3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
